many fixes and improvements - code and test units
- the process of transferring test units in separate files - testini.sh,
  teststd.sh & etc
- detected subtle bugs (from r172) - arguments should not coincide with
  the names of local variables in a function that returns the result in
  the variable identifier. Local variables are randomized to prevent
  masking of similar variables outside

Makefile.am:
- added testini.sh, teststd.sh to assembly

libstd.sh:
- added new function udfIsValidVariable - to verify the validity of the
  identifiers for variables
- updated function udfIsNumber - fixed robodoc section
- test unit moved to teststd.sh

libini.sh:
- test unit moved to testini.sh
- updated functions udfReadiniSection, udfCheckCsv:
  * key fields of the configuration ini files with spaces no longer be
    ignored, and treated as a "simple" raw data
  * updated/added robodoc section
- updated function udfCheckCsv - randomized all local variables
- updated function udfCsvOrder - remove empty field
- updated function udfSetVarFromCsv - support for perl regular
  expressions (grep -P) is no longer required

bashlyk:
- testing is performed by calling the file test<lib>.sh
- if you chose testing (--bashlyk-test = ...), after the test script
  terminates without performing the main body of the script
- updated robodoc section
- randomized some local variables that could potentially be changed when
  connecting libraries and test units

diff --git a/src/bashlyk b/src/bashlyk
--- a/src/bashlyk
+++ b/src/bashlyk
@@ -32,17 +32,18 @@
 #  SYNOPSIS
 #    udfInit
 #  DESCRIPTION
-#    Подготовка к запуску сценария, определение условий его работы
-#    (каталоги расположения создаваемых файлов, наличие терминала, перенаправления и т.п.)
-#    Если запуск выполняется от "root", то каталоги располагаются глобально, согласно LSB, 
-#    иначе - в каталоге ~/.bashlyk или во временном каталоге, если не удалось определить
-#    владельца процесса
+#    Подготовка к запуску сценария, определение условий его работы (каталоги 
+#    расположения создаваемых файлов, наличие терминала, перенаправления и т.п.)
+#    Если запуск выполняется от "root", то каталоги располагаются глобально,
+#    согласно LSB, иначе - в каталоге ~/.bashlyk или во временном каталоге, если
+#    не удалось определить владельца процесса
 #  SOURCE
 udfInit() {
  local pathCnf pathRoot pathRun pathLog pathDat sHome
  #
  _bashlyk_sId=${_bashlyk:-bashlyk}
- [ -n "$_bashlyk" ] && _bashlyk_pathPrefix="/${_bashlyk}" || _bashlyk_pathPrefix=
+ [ -n "$_bashlyk" ] && _bashlyk_pathPrefix="/${_bashlyk}" \
+  || _bashlyk_pathPrefix=
  pathCnf="etc${_bashlyk_pathPrefix}"
  pathLog="var/log${_bashlyk_pathPrefix}"
  pathRun="var/run${_bashlyk_pathPrefix}"
@@ -87,14 +88,25 @@ udfInit() {
 #    в зависимости от значения $_bashlyk_sCond4Log ("noterm" по умолчанию).
 #  SOURCE
 udfMain() {
- local fn fnLib
+ local aIncinpj8Ive fn s sModeYs8vfIqM='lib'
  #
  udfInit
  #
- for fn in $(echo ${_bashlyk_aLib} | tr ',' ' '); do
-  fnLib="${_bashlyk_pathLib}/lib${fn}.sh"
-  [ -s $fnLib ] && . $fnLib || eval 'echo "error with $fnLib using"; exit 255'
+ aIncinpj8Ive="$(echo "${_bashlyk_sArg#*--bashlyk-test=}" | cut -f1 -d' ' | tr ',' ' ')"
+
+ if [ -n "$aIncinpj8Ive" ]; then
+  sModeYs8vfIqM='test'
+ else
+  aIncinpj8Ive="$(echo ${_bashlyk_aLib} | tr ',' ' ')"
+ fi
+
+ for s in $aIncinpj8Ive; do
+  fn=${_bashlyk_pathLib}/${sModeYs8vfIqM}${s}.sh
+  [ -s $fn ] && . $fn || eval 'echo "Error: $fn not found..."; exit 255'
  done
+
+ [ "$sModeYs8vfIqM" = "test" ] && exit 0
+
  case ${_bashlyk_sCond4Log} in
   redirect)
            _bashlyk_bNotUseLog=$_bashlyk_bInteract ;;
